[package]
name = "strofa"
version = "0.1.0"
edition = "2021"

[dependencies]
tui = { version = "0.17.0", features = ["crossterm"], default-features = false }
crossterm = "0.22.1"
serde = { version = "1.0", features = ["derive"] }
zmerald = { path="../zmerald" }